server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.23.144.228:3306/server?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: remote
    password: YeKe1403483531.

mybatis-flex:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl